spring:
  r2dbc:
    url: jdbc:postgresql://localhost:65432/postgres
    username: postgres
    password: postgres
    pool:
      min-idle: 10
      max-size: 100
      validation-query: SELECT 1
  docker:
    compose:
      file: "../../docker/compose.yaml"
