feature-flags:
  feature-names:
    greeting: true
    new-search: true
    new-export: false
    legacy-api: false
    special-endpoint: true
    json-demo: false
    plain-text-demo: false
    html-demo: false
