spring:
  datasource:
    url: jdbc:postgresql://localhost:65432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      connection-init-sql: SELECT 1
  docker:
    compose:
      file: "../../docker/compose.yaml"

mybatis:
  mapper-locations: classpath*:/net/brightroom/example/*.xml
  configuration:
    map-underscore-to-camel-case: true
